config/routes.rb
Rails.application.routes.draw do

    scope "(:locale)",locale: /vi|en/ do
  	root "room_chats#index"
    mount ActionCable.server => "/cable"

  	resources :static_pages
    resources :room_chats
    resources :messages
    resources :profiles, only: [:edit, :update]
    resources :message_notifications, only: [:index]
    resources :reset_passwords, only: [:edit, :update]
    resources :requests
    resources :reports
    resources :manage_projects
    resources :add_members
    resources :company_projects
    resources :project_members
    resources :add_project_managers
    resources :add_project_members
    resources :add_project_divisions
    resources :manage_divisions
    resources :show_projects
    resources :show_profiles
    resources :project_divisions
    resources :show_reports
    resources :approval_requests
    resources :division_projects
    resources :overview_companys
    resources :share_tasks
    resources :overview_divisions
    resources :overview_personals
    resources :errors, ony: [:index]
    resources :division_members
    resources :project_division_members
    resources :division_reports
    resources :division_tasks
    resources :add_task_users
    resources :personal_tasks
    resources :add_personal_tasks
    resources :my_calendars
    resources :my_works
    resources :user_managers
    resources :overview_projects
    resources :project_reports
    resources :project_tasks
    resources :project_requests
    resources :company_tasks
    resources :company_reports
    resources :company_members
    resources :show_view_progress
    devise_for :users
  end
  # get 'static_pages/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/project_request.rb
class ProjectRequest < ApplicationRecord
  PARAMS = %i(title description document_link client_company division_id project_id project_leader).freeze

  belongs_to :project
  belongs_to :division

  validates :title, presence: true, length: {maximum: 255}
  validates :division_id, presence: true
  validates :project_id, presence: true
  validates :description, presence: true
  validates :client_company, presence: true, length: {maximum: 255}
  validates :document_link, presence: true, length: {maximum: 255}
end

app/controllers/project_requests_controller.rb
class ProjectRequestsController < ApplicationController
  before_action :authenticate_user!

  def index
    if current_user.member?
      @q = current_user.projects.first&.project_requests.ransack(params[:q])
      @requests = @q.result(distinct: true).paginate(page: params[:page], per_page: 7)
    else
      @q = current_division.project_requests.ransack(params[:q])
      @requests = @q.result(distinct: true).paginate(page: params[:page], per_page: 7)
    end
  end

  def show
    @project_request = ProjectRequest.find_by id: params[:id]
    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    @project_request = ProjectRequest.new
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @project_request = current_user.projects.first.project_requests.new params_project_request
    if @project_request.save
      flash[:success] = "Bạn tạo yêu cầu thành công"
      redirect_to project_requests_path
    else
      render :new
    end
  end

  def edit
    @project_request = ProjectRequest.find_by id: params[:id]
    respond_to do |format|
      format.html
      format.js
    end
  end

  def update
    @project_request = ProjectRequest.find_by id: params[:id]
    params_project_request.merge(project_id: current_user.projects.first.id)
    if @project_request.update params_project_request
      flash[:success] = "Cập nhật thành công"
      redirect_to project_requests_path
    else
      render :edit
    end

  end

  private

  def params_project_request
    params.require(:project_request).permit ProjectRequest::PARAMS
  end

  def correct_project_leader
    unless current_user.member? && current_division.is_project?
      redirect_to root_path
    end
  end
end

app/views/project_requests/_edit.html.erb
<div class="card">
<div class="card-body">
  <div class="tab-content">
    <div class="active tab-pane" id="settings">
      <%= form_for(@project_request, url: project_request_path, class: "form-horizontal", remote: true) do |f|%>
        <%= render "shared/error_messages", object: f.object %>

        <%= f.hidden_field :project_id, class: "form-control", value: "#{current_user.projects.first.id}" %>
        <div class="form-group row">
          <div class="col-sm-2">
            <%= f.label :title, class: "col-form-label" %>
          </div>
          <div class="col-sm-10">
            <%= f.text_field :title, class: "form-control", placeholder:"Title" %>
          </div>
        </div>


        <div class="form-group row">
          <%= f.label :division_id, class: "col-sm-2 col-form-label" %>
          <div class="col-sm-4">
            <%= f.select :division_id, division_request_select.collect{|i| [i.name, i.id]},{}, {class: "form-control custom-select", disabled: true}  %>
          </div>

          <label for="country" class="col-sm-2">Project</label>
          <div class="col-sm-4">
            <input class="form-control" id="country" readonly value="<%= current_user.projects.first.name %>">
          </div>
        </div>

        <div class="form-group row">
          <div class="col-sm-2">
            <%= f.label :client_company, class: "col-form-label" %>
          </div>
          <div class="col-sm-4">
            <%= f.text_field :client_company, class: "form-control", value: "#{current_user.projects.first.client_company}", readonly: true%>
          </div>

          <div class="col-sm-2">
            <%= f.label :project_leader, class: "col-form-label" %>
          </div>
          <div class="col-sm-4">
            <%= f.text_field :project_leader, {class: "form-control", value: "#{current_user.name}", readonly: true} %>
          </div>
        </div>

        <div class="form-group row">
          <div class="col-sm-2">
            <%= f.label :document_link, class: "col-form-label" %>
          </div>
          <div class="col-sm-10">
            <%= f.text_field :document_link, {class: "form-control", value: "#{current_user.name}"} %>
          </div>
        </div>

        <div class="form-group row">
          <div class="col-sm-2">
            <%= f.label :description, class: "col-form-label" %>
          </div>
          <div class="col-sm-10">
            <%= f.text_area :description, class: "form-control", placeholder:"Description" %>
          </div>
        </div>


        <div class="form-group row">
          <div class="offset-sm-2 col-sm-10">
            <%= f.submit "Cập nhật", class: "btn btn-success" %>
          </div>
        </div>
      <% end %>
    </div>
    <!-- /.tab-pane -->
  </div>
  <!-- /.tab-content -->
</div><!-- /.card-body -->
</div>

app/views/project_requests/_new.html.erb
<div class="card">
<div class="card-body">
  <div class="tab-content">
    <div class="active tab-pane" id="settings">
      <%= form_for(@project_request, url: project_requests_path, class: "form-horizontal", remote: true) do |f|%>
        <%= render "shared/error_messages", object: f.object %>
        <div class="form-group row">
          <div class="col-sm-2">
            <%= f.label :title, class: "col-form-label" %>
          </div>
          <div class="col-sm-10">
            <%= f.text_field :title, class: "form-control", placeholder:"Title" %>
          </div>
        </div>


        <div class="form-group row">
          <%= f.label :division_id, class: "col-sm-2 col-form-label" %>
          <div class="col-sm-4">
            <%= f.select :division_id, division_request_select.collect{|i| [i.name, i.id]},{}, {class: "form-control custom-select"}  %>
          </div>

          <%= f.label :project_id, class: "col-sm-2 col-form-label" %>
          <div class="col-sm-4">
             <%= f.text_field :project_id, class: "form-control", value: "#{current_user.projects.first.name}", readonly: true %>
          </div>
        </div>

        <div class="form-group row">
          <div class="col-sm-2">
            <%= f.label :client_company, class: "col-form-label" %>
          </div>
          <div class="col-sm-4">
            <%= f.text_field :client_company, class: "form-control", value: "#{current_user.projects.first.client_company}", readonly: true %>
          </div>

          <div class="col-sm-2">
            <%= f.label :project_leader, class: "col-form-label" %>
          </div>
          <div class="col-sm-4">
            <%= f.text_field :project_leader, {class: "form-control", value: "#{current_user.name}", readonly: true} %>
          </div>
        </div>

        <div class="form-group row">
          <div class="col-sm-2">
            <%= f.label :document_link, class: "col-form-label" %>
          </div>
          <div class="col-sm-10">
            <%= f.text_field :document_link, {class: "form-control", value: "#{current_user.name}"} %>
          </div>
        </div>

        <div class="form-group row">
          <div class="col-sm-2">
            <%= f.label :description, class: "col-form-label" %>
          </div>
          <div class="col-sm-10">
            <%= f.text_area :description, class: "form-control", placeholder:"Description" %>
          </div>
        </div>


        <div class="form-group row">
          <div class="offset-sm-2 col-sm-10">
            <%= f.submit "Tạo Yêu Cầu", class: "btn btn-success" %>
          </div>
        </div>
      <% end %>
    </div>
    <!-- /.tab-pane -->
  </div>
  <!-- /.tab-content -->
</div><!-- /.card-body -->
</div>

app/views/project_requests/_request.html.erb
<tr class="hidden_content">
  <td><%= request_counter + 1 %></td>
  <td><%= request.title %></td>
  <td><%= request.project.name %></td>
  <td><%= request.division.name %></td>
  <td><%= request.client_company %></td>
  <td><%= request.description %></td>


  <td class="project-actions text-right">
    <%= link_to project_request_path(request), {class: "btn btn-primary btn-sm", remote: :true, "data-toggle": "modal", "data-target": "#show_dialog"} do %>
      <i class="fas fa-eye">
      </i>
      View
    <% end %>
    <% if current_user.member? %>
      <%= link_to edit_project_request_path(request), {class: "btn btn-info btn-sm", remote: :true, "data-toggle": "modal", "data-target": "#show_dialog"} do %>
        <i class="fas fa-pencil-alt">
        </i>
        Edit
      <% end %>
    <% end %>
  </td>
</tr>

app/views/project_requests/_show.html.erb
<div class="card">
<div class="card-body">
  <div class="tab-content">
    <div class="active tab-pane" id="settings">
      <%= form_for(@project_request, url: project_request_path, class: "form-horizontal", remote: true) do |f|%>
        <%= render "shared/error_messages", object: f.object %>

        <%= f.hidden_field :project_id, class: "form-control", value: "#{current_user.projects.first.id}" %>
        <div class="form-group row">
          <div class="col-sm-2">
            <%= f.label :title, class: "col-form-label" %>
          </div>
          <div class="col-sm-10">
            <%= f.text_field :title, class: "form-control", placeholder:"Title", readonly: true %>
          </div>
        </div>


        <div class="form-group row">
          <%= f.label :division_id, class: "col-sm-2 col-form-label" %>
          <div class="col-sm-4">
            <%= f.select :division_id, division_request_select.collect{|i| [i.name, i.id]},{}, {class: "form-control custom-select", readonly: true}  %>
          </div>

          <label for="country" class="col-sm-2">Project</label>
          <div class="col-sm-4">
            <input class="form-control" id="country" readonly value="<%= current_user.projects.first.name %>">
          </div>
        </div>

        <div class="form-group row">
          <div class="col-sm-2">
            <%= f.label :client_company, class: "col-form-label" %>
          </div>
          <div class="col-sm-4">
            <%= f.text_field :client_company, class: "form-control", placeholder:"Link Pull Request", readonly: true %>
          </div>

          <div class="col-sm-2">
            <%= f.label :project_leader, class: "col-form-label" %>
          </div>
          <div class="col-sm-4">
            <%= f.text_field :project_leader, {class: "form-control", value: "#{current_user.name}", readonly: true} %>
          </div>
        </div>

        <div class="form-group row">
          <div class="col-sm-2">
            <%= f.label :document_link, class: "col-form-label" %>
          </div>
          <div class="col-sm-10">
            <%= f.text_field :document_link, {class: "form-control", value: "#{current_user.name}", readonly: true} %>
          </div>
        </div>

        <div class="form-group row">
          <div class="col-sm-2">
            <%= f.label :description, class: "col-form-label" %>
          </div>
          <div class="col-sm-10">
            <%= f.text_area :description,style: "height: 150px;", class: "form-control", placeholder:"Description", readonly: true %>
          </div>
        </div>
      <% end %>
    </div>
    <!-- /.tab-pane -->
  </div>
  <!-- /.tab-content -->
</div><!-- /.card-body -->
</div>

app/views/project_requests/edit.js.erb
$("#title_dialog").text("Chỉnh sửa yêu cầu cho bộ phận");
$(".modal-dialog.modal-dialog-centered").css("max-width", "900px");
$("#modal_body").html("<%= j(render :partial => "project_requests/edit")%>");

app/views/project_requests/index.html.erb
<div class="content-wrapper">
  <% if current_user.member? %>
    <%= render partial: "shared/head_profile", locals: {path1: overview_projects_path, title: "Quản lý task dự án thuộc dự án", link1: "Quản lý dự án", link2: "Danh sách Tasks"}%>
  <% else %>
    <%= render partial: "shared/head_profile", locals: {path1: overview_divisions_path, title: "Quản lý task dự án thuộc dự án", link1: "Quản lý bộ phận", link2: "Danh sách Tasks"}%>
  <% end %>

    <section class="content">

      <div class="card container">
        <div class="card-body">
          <div class="row">
            <div class="col-12 col-md-12 col-lg-12 order-2 order-md-1">
              <div class="row">
                <div class="col-md-12">
                  <div class="row float-right" style="margin: 0 0 10px 0px;">
                    <%= search_form_for @q, url: project_tasks_path, class: "form-inline", method: :get do |f| %>
                      <%= f.search_field :title_cont, class: "form-control mr-sm-2", placeholder: "Search" %>
                      <%= f.submit class: "btn btn-outline-success my-2 mr-sm-2 my-sm-0" %>
                    <% end %>
                  </div>

                  <div class="card" style="width: 100%">
                    <!-- /.card-header -->
                    <div class="card-body p-0">
                      <div class="table-responsive">
                        <table class="table m-0 table-striped projects">
                          <thead>
                          <tr style="color: #17a2b8;">
                            <th>#</th>
                            <th>Title</th>
                            <th>Project</th>
                            <th>Division</th>
                            <th>Document Link</th>
                            <th>Description</th>
                            <th class="text-center" style="width: 20%">More</th>
                          </tr>
                          </thead>
                          <tbody>
                            <%= render partial: "project_requests/request", collection: @requests %>
                          </tbody>
                        </table>
                      </div>
                      <!-- /.table-responsive -->
                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer clearfix">
                      <div id="pagina" class="btn btn-sm">
                        <%= link_to new_project_request_path, {class: "btn btn-sm btn-info float-left", remote: true, "data-toggle": "modal", "data-target": "#show_dialog"} do %>
                         <i class="fas fa-tasks"></i>
                          Thêm yêu cầu cho dự án
                        <% end %>
                      </div>
                      <div class="float-right">
                        <%= will_paginate @requests if @requests %>
                      </div>
                    </div>
                    <!-- /.card-footer -->
                  </div>
                  <!-- /.card -->
                </div>
              </div>
            </div>

          </div>
        </div>
        <!-- /.card-body -->
      </div>
      <!-- /.card -->
    </section>
    <!-- /.content -->
  </div>

app/views/project_requests/new.js.erb
$("#title_dialog").text("Tạo yêu cầu cho bộ phận");
$(".modal-dialog.modal-dialog-centered").css("max-width", "900px");
$("#modal_body").html("<%= j(render :partial => "project_requests/new")%>");

app/views/project_requests/show.js.erb
$("#title_dialog").text("Xem yêu cầu");
$(".modal-dialog.modal-dialog-centered").css("max-width", "900px");
$("#modal_body").html("<%= j(render :partial => "project_requests/show")%>");