config/routes.rb
Rails.application.routes.draw do

    scope "(:locale)",locale: /vi|en/ do
  	root "room_chats#index"
    mount ActionCable.server => "/cable"

  	resources :static_pages
    resources :room_chats
    resources :messages
    resources :profiles, only: [:edit, :update]
    resources :message_notifications, only: [:index]
    resources :reset_passwords, only: [:edit, :update]
    resources :requests
    resources :reports
    resources :manage_projects
    resources :add_members
    resources :company_projects
    resources :project_members
    resources :add_project_managers
    resources :add_project_members
    resources :add_project_divisions
    resources :manage_divisions
    resources :show_projects
    resources :show_profiles
    resources :project_divisions
    resources :show_reports
    resources :approval_requests
    resources :division_projects
    resources :overview_companys
    resources :share_tasks
    resources :overview_divisions
    resources :overview_personals
    resources :errors, ony: [:index]
    resources :division_members
    resources :project_division_members
    resources :division_reports
    resources :division_tasks
    resources :add_task_users
    resources :personal_tasks
    resources :add_personal_tasks
    resources :my_calendars
    resources :my_works
    resources :user_managers
    resources :overview_projects
    resources :project_reports
    resources :project_tasks
    resources :project_requests
    resources :company_tasks
    resources :company_reports
    resources :company_members
    resources :show_view_progress
    devise_for :users
  end
  # get 'static_pages/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/controllers/overview_companys_controller.rb
class OverviewCompanysController < ApplicationController
  before_action :authenticate_user!
  before_action :count_overview, only: [:index]
  before_action :time_line, only: [:index]
  before_action :pie_chart_project, only: [:index]
  before_action :correct_boss

  def index
    @q = Project.ransack(params[:q])
    @projects = @q.result(distinct: true).paginate(page: params[:page], per_page: 7)
  end

  private

  def time_line
    @time_line = []
    @projects = Project.all
    @projects.each do |project|
      start_time = project.tasks.where(parent_task: true).minimum('start_time')
      end_time = project.tasks.where(parent_task: true).maximum('end_time')
      if start_time.present? && end_time.present?
        @time_line.push(["#{project.name}", "#{start_time}", "#{end_time + 1.days}"])
      end
    end
  end

  def pie_chart_project
    @pie_chart_project = []
    @projects = Project.all
    @projects.each do |project|
      pie_chart_division = []
      project.divisions.uniq.each do |division|
        pie_chart_division.push(["#{division.name}", "#{division.users.where(id: project.users).count}"])
      end
      @pie_chart_project.push(pie_chart_division)
    end
    @sum_pie = @pie_chart_project.count - 1
  end

  def count_overview
    @project_count = Project.all.count
    @report_count = Report.all.count
  end

  def correct_boss
    unless current_user.manager? && current_division.is_project?
      redirect_to root_path
    end
  end
end

app/views/overview_companys/_project.html.erb
<tr class="hidden_content">
  <td><%= project_counter + 1 %></td>
  <td><%= project.name %></td>
  <td>
    <% if project.medium? %>
      <span class="badge badge-success"><%= project.importance %></span>
    <% else %>
      <span class="badge badge-danger"><%= project.importance %></span>
    <% end %>
  </td>

  <td><%= project.client_company %></td>
  <td><%= project.document_link %></td>
  <td><%= project.description %></td>
  <td><b class="text-success"><%= "#{expected_project(project)} %" %></b></td>

  <td><b class="text-danger"><%= "#{progress_project(project)} %" %></b></td>

  <td class="project-actions text-right" style="max-width: 150px;">
    <%= link_to company_project_path(project), {class: "btn btn-sm btn-info", remote: true, "data-toggle": "modal", "data-target": "#show_dialog"} do %>
      <i class="fas fa-eye">
      </i>
      <%= t".describe"%>
    <% end %>
  </td>
</tr>

app/views/overview_companys/index.html.erb
 <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <%= render partial: "shared/head_profile", locals: {path1: room_chats_path, title: t(".title"), link1: t(".link1"), link2: ""}%>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <!-- Info boxes -->
        <div class="row">
          <div class="col-12 col-sm-6 col-md-6">
            <%= link_to company_reports_path, style: "text-decoration: none; color: #212529" do %>
              <div class="info-box mb-3">
                <span class="info-box-icon bg-danger elevation-1"><i class="fas fa-user-edit"></i></span>
                <div class="info-box-content">
                  <span class="info-box-text"><%= t".reports"%></span>
                  <span class="info-box-number">
                  <%= @report_count %>
                  <small><%= t".report"%></small>
                </div>
                <!-- /.info-box-content -->
              </div>
            <% end %>
          </div>
          <!-- /.col -->

          <!-- fix for small devices only -->
          <div class="clearfix hidden-md-up"></div>

          <div class="col-12 col-sm-6 col-md-6">
            <%= link_to company_projects_path, style: "text-decoration: none; color: #212529" do %>
              <div class="info-box mb-3">
                <span class="info-box-icon bg-success elevation-1"><i class="fas fa-project-diagram"></i></span>

                <div class="info-box-content">
                  <span class="info-box-text"><%= t".projects"%></span>
                  <span class="info-box-number">
                  <%= @project_count %>
                  <small><%= t".project"%></small>
                </span>
                </div>
                <!-- /.info-box-content -->
              </div>
            <% end %>
          </div>
        </div>

        <!-- /.row -->
        <div class="row">
          <div class="col-12">
            <!-- jQuery Knob -->
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">
                  <%= t".time_line"%>
                </h3>

                <div class="card-tools">
                  <button type="button" class="btn btn-tool" data-card-widget="collapse"><i
                      class="fas fa-minus"></i>
                  </button>

                </div>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <%= timeline @time_line %>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
          <!-- /.col -->
        </div>

        <div class="card">
          <div class="card-body">
            <div class="row">
              <div class="col-12 col-md-12 col-lg-12 order-2 order-md-1">
                <div class="row">
                  <div class="col-md-12">

                    <div class="float-left"><%= will_paginate @projects if @projects %></div>
                    <div class="float-right" style="margin: 0 0 10px 0px;">
                      <%= search_form_for @q, url: overview_companys_path, class: "form-inline", method: :get do |f| %>
                        <%= f.search_field :name_cont, class: "form-control mr-sm-2", placeholder: "Search" %>
                        <%= f.submit class: "btn btn-outline-success my-2 mr-sm-2 my-sm-0" %>
                      <% end %>
                    </div>

                    <div class="card" style="width: 100%">
                      <!-- /.card-header -->
                      <div class="card-body p-0">
                        <div class="table-responsive">
                          <table class="table m-0 table-striped projects">
                            <thead>
                            <tr>
                              <th>#</th>
                              <th><%= t".name"%></th>
                              <th><%= t".importance"%></th>
                              <th><%= t".client_company"%></th>
                              <th><%= t".document_link"%></th>
                              <th><%= t".description"%></th>
                              <th><%= t".expected"%></th>
                              <th><%= t".progress"%></th>

                              <th><%= t".more"%></th>
                            </tr>
                            </thead>
                            <tbody id="show-task-pr">
                              <%= render partial: "overview_companys/project", collection: @projects %>
                            </tbody>
                          </table>
                        </div>
                        <!-- /.table-responsive -->
                      </div>
                      <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                  </div>
                </div>
              </div>

            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-md-12">
            <div class="card">
              <div class="card-header">
                <h5 class="card-title"><%= t".percentage"%></h5>

                <div class="card-tools">
                  <button type="button" class="btn btn-tool" data-card-widget="collapse">
                    <i class="fas fa-minus"></i>
                  </button>
                </div>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <div class="row">
                  <%= (0..@sum_pie).each do |i| %>
                    <div class="chart col-md-6">
                      <%= pie_chart @pie_chart_project[i], donut: true %>
                    </div>
                  <% end %>
                </div>
                <!-- /.row -->
              </div>
              <!-- ./card-body -->
            </div>
            <!-- /.card -->
          </div>
          <!-- /.col -->
        </div>

      </div><!--/. container-fluid -->
    </section>
    <!-- /.content -->
  </div>