config/routes.rb
Rails.application.routes.draw do

    scope "(:locale)",locale: /vi|en/ do
  	root "room_chats#index"
    mount ActionCable.server => "/cable"

  	resources :static_pages
    resources :room_chats
    resources :messages
    resources :profiles, only: [:edit, :update]
    resources :message_notifications, only: [:index]
    resources :reset_passwords, only: [:edit, :update]
    resources :requests
    resources :reports
    resources :manage_projects
    resources :add_members
    resources :company_projects
    resources :project_members
    resources :add_project_managers
    resources :add_project_members
    resources :add_project_divisions
    resources :manage_divisions
    resources :show_projects
    resources :show_profiles
    resources :project_divisions
    resources :show_reports
    resources :approval_requests
    resources :division_projects
    resources :overview_companys
    resources :share_tasks
    resources :overview_divisions
    resources :overview_personals
    resources :errors, ony: [:index]
    resources :division_members
    resources :project_division_members
    resources :division_reports
    resources :division_tasks
    resources :add_task_users
    resources :personal_tasks
    resources :add_personal_tasks
    resources :my_calendars
    resources :my_works
    resources :user_managers
    resources :overview_projects
    resources :project_reports
    resources :project_tasks
    resources :project_requests
    resources :company_tasks
    resources :company_reports
    resources :company_members
    resources :show_view_progress
    devise_for :users
  end
  # get 'static_pages/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/controllers/overview_projects_controller.rb
class OverviewProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :count_overview, only: [:index]

  def index
    @tasks = current_user.projects.first.tasks.where(parent_task: true, active: true)
    @divisions = current_user.projects.first.divisions.uniq
    time_line @tasks
    pie_chart_division @divisions, current_user.projects.first
    pie_chart_task_division @divisions
  end

  private

  def pie_chart_task_division divisions
    @pie_chart_task_division = []
    divisions.each do |division|
      @pie_chart_task_division.push(["#{division.name}", "#{sum_task(division.tasks.where(parent_task: true))}"])
    end
  end

  def sum_task tasks
    # progress = tasks.inject(0) do |sum, task|
    #   sum + task.progress * (task.start_time..task.end_time).count
    # end

    days = tasks.inject(0) do |sum, task|
      sum + (task.start_time..task.end_time).count
    end
    return days if days != 0
    return 0
  end

  def pie_chart_division divisions, project
    @pie_chart_division = []
    divisions.each do |division|
      @pie_chart_division.push(["#{division.name}", "#{division.users.where(id: project.users).count}"])
    end
  end

  def time_line tasks
    @time_line = []
    tasks.each do |task|
      @time_line.push(["#{task.title}", "#{task.start_time}", "#{task.end_time + 1.days}"])
    end
  end

  def count_overview
    @sum_request = current_division.approval_requests.where(send_for: 0).uniq.count
    @sum_member = current_user.projects.first.users.uniq.count
    @sum_report = current_user.projects.first.reports.uniq.count
    @sum_task = current_user.projects.first.tasks.where(parent_task: true).uniq.count
  end
end

app/views/overview_projects/index.html.erb
 <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <%= render partial: "shared/head_profile", locals: {path1: room_chats_path, title: t(".title"), link1: t(".link1"), link2: t(".link2")}%>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <!-- Info boxes -->
        <div class="row">
          <div class="col-12 col-sm-6 col-md-3">
          <%= link_to project_tasks_path, style: "text-decoration: none; color: #333333" do %>
            <div class="info-box">
              <span class="info-box-icon bg-info elevation-1"><i class="fas fa-tasks"></i></span>

              <div class="info-box-content">
                <span class="info-box-text"><%= t".tasks"%></span>
                <span class="info-box-number">
                 <span class="info-box-number"><%= @sum_task %></span>
                </span>
              </div>
              <!-- /.info-box-content -->
            </div>
          <% end %>
          </div>
          <!-- /.col -->
          <div class="col-12 col-sm-6 col-md-3">
            <%= link_to project_reports_path, style: "text-decoration: none; color: #333333" do %>
              <div class="info-box mb-3">
                <span class="info-box-icon bg-danger elevation-1"><i class="fas fa-user-edit"></i></span>
                <div class="info-box-content">
                  <span class="info-box-text"><%= t".reports"%></span>
                  <span class="info-box-number"><%= @sum_report %></span>
                </div>
                <!-- /.info-box-content -->
              </div>
            <% end %>
          </div>
          <!-- /.col -->

          <!-- fix for small devices only -->
          <div class="clearfix hidden-md-up"></div>

          <div class="col-12 col-sm-6 col-md-3">
            <%= link_to approval_requests_path, style: "text-decoration: none; color: #333333" do %>
              <div class="info-box mb-3">
                <span class="info-box-icon bg-success elevation-1"><i class="fas fa-user-tag"></i></span>

                <div class="info-box-content">
                  <span class="info-box-text"><%= t".requests"%></span>
                  <span class="info-box-number"><%= @sum_request %></span>
                </div>
                <!-- /.info-box-content -->
              </div>
            <% end %>
          </div>
          <!-- /.col -->
          <div class="col-12 col-sm-6 col-md-3">
            <%= link_to project_members_path, style: "text-decoration: none; color: #333333" do %>
              <div class="info-box mb-3">
                <span class="info-box-icon bg-warning elevation-1"><i class="fas fa-users"></i></span>
                <div class="info-box-content">
                  <span class="info-box-text"><%= t".members"%></span>
                  <span class="info-box-number"><%= @sum_member %></span>
                </div>
                <!-- /.info-box-content -->
              </div>
            <% end %>
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->

        <div class="card">
          <div class="card-header">
            <h3 class="card-title">
              <i class="far fa-chart-bar"></i>
              jQuery Knob
            </h3>

            <div class="card-tools">
              <button type="button" class="btn btn-tool" data-card-widget="collapse"><i
                  class="fas fa-minus"></i>
              </button>

            </div>
          </div>
          <!-- /.card-header -->
          <div class="card-body">
            <%= timeline @time_line %>
          </div>
          <!-- /.card-body -->
        </div>

        <div class="row">
          <div class="col-md-6">
            <!-- AREA CHART -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title"><%= t".time_task"%></h3>

                <div class="card-tools">
                  <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i>
                  </button>
                  <button type="button" class="btn btn-tool" data-card-widget="remove"><i class="fas fa-times"></i></button>
                </div>
              </div>
              <div class="card-body">
                <div class="chart">
                  <%= pie_chart @pie_chart_task_division, donut: true %>
                </div>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>

           <div class="col-md-6">
            <!-- AREA CHART -->
            <div class="card card-info">
              <div class="card-header">
                <h3 class="card-title"><%= t".member_join"%></h3>

                <div class="card-tools">
                  <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i>
                  </button>
                  <button type="button" class="btn btn-tool" data-card-widget="remove"><i class="fas fa-times"></i></button>
                </div>
              </div>
              <div class="card-body">
                <div class="chart">
                  <%= pie_chart @pie_chart_division, donut: true %>
                </div>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>


        <!-- /.row -->
      </div><!--/. container-fluid -->
    </section>
    <!-- /.content -->
  </div>