config/routes.rb
Rails.application.routes.draw do

    scope "(:locale)",locale: /vi|en/ do
  	root "room_chats#index"
    mount ActionCable.server => "/cable"

  	resources :static_pages
    resources :room_chats
    resources :messages
    resources :profiles, only: [:edit, :update]
    resources :message_notifications, only: [:index]
    resources :reset_passwords, only: [:edit, :update]
    resources :requests
    resources :reports
    resources :manage_projects
    resources :add_members
    resources :company_projects
    resources :project_members
    resources :add_project_managers
    resources :add_project_members
    resources :add_project_divisions
    resources :manage_divisions
    resources :show_projects
    resources :show_profiles
    resources :project_divisions
    resources :show_reports
    resources :approval_requests
    resources :division_projects
    resources :overview_companys
    resources :share_tasks
    resources :overview_divisions
    resources :overview_personals
    resources :errors, ony: [:index]
    resources :division_members
    resources :project_division_members
    resources :division_reports
    resources :division_tasks
    resources :add_task_users
    resources :personal_tasks
    resources :add_personal_tasks
    resources :my_calendars
    resources :my_works
    resources :user_managers
    resources :overview_projects
    resources :project_reports
    resources :project_tasks
    resources :project_requests
    resources :company_tasks
    resources :company_reports
    resources :company_members
    resources :show_view_progress
    devise_for :users
  end
  # get 'static_pages/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/controllers/company_projects_controller.rb
class CompanyProjectsController < ApplicationController

  before_action :authenticate_user!

  def index
    @q = Project.ransack(params[:q])
    @projects = @q.result.paginate(page: params[:page], per_page: 5)
  end

  def new
    @project = Project.new
    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    @project = Project.find_by id: params[:id]
    respond_to do |format|
      format.html
      format.js
    end
    # @leaders = @project.users.where(@project.user_projects.where(role: 1))
  end


  def create
    @project = Project.new project_params
    ActiveRecord::Base.transaction do
      @project.save!
      create_room_chat @project
      flash[:success] = "Khởi tạo dự án thành công"
      redirect_to company_projects_path
    rescue ActiveRecord::RecordInvalid
      render :new
    end
  end

  def edit
    @project = Project.find_by id: params[:id]
    respond_to do |format|
      format.html
      format.js
    end
  end

  def update
    @project = Project.find_by id: params[:id]
    if @project.update project_params
      flash[:success] = "Cập nhật dự án thành công"
      redirect_to company_projects_path
    else
      flash[:error] = "Cập nhật dự án thất bại"
      render :edit
    end
  end

  def destroy
    @project = Project.find_by id: params[:id]
    ActiveRecord::Base.transaction do
      @project.destroy!
      delete_room_chat @project
      flash[:success] = "Xóa dự án thành công"
      redirect_to company_projects_path
    rescue ActiveRecord::RecordInvalid
      flash[:error] = "Xóa dự án thất bại"
      redirect_to root_path
    end
  end

  private

  def create_room_chat project
    list = ListMessage.create!(name: project.name, type_mes: 1)
    Message.create!(content: "#{current_user.name} đã tham gia dự án", list_message_id: list.id, user_id: current_user.id)
  end

  def delete_room_chat project
    @list = ListMessage.find_by name: project.name
    @list.destroy! if @list.present?
  end

  def project_params
    params.require(:project).permit Project::PARAMS
  end

  def correct_boss
    unless current_user.manager? && current_division.is_project?
      redirect_to root_path
    end
  end
end

app/views/company_projects/_division.html.erb
<li class="list-inline-item">
  <%= image_tag "#{division.image}", class: "table-avatar" %>
</li>

app/views/company_projects/_edit.html.erb
<div class="card-body" style="margin: 20px 0px;">
  <div class="tab-content">
    <div class="active tab-pane" id="settings">
      <%= form_for(@project, url: company_project_path, class: "form-horizontal", remote: true) do |f|%>
        <%= render "shared/error_messages", object: f.object %>
        <%= f.hidden_field :path, value: @path %>
        <div class="form-group row">
          <div class="col-sm-2">
            <%= f.label :name, class: "col-form-label" %>
          </div>
          <div class="col-sm-10">
            <%= f.text_field :name, class: "form-control", placeholder:"Project Name", readonly: true %>
          </div>
        </div>

        <div class="form-group row">
          <div class="col-sm-2">
            <%= f.label :document_link, class: "col-form-label" %>
          </div>
          <div class="col-sm-10">
            <%= f.text_area :document_link, class: "form-control", placeholder:"Document Link" %>
          </div>
        </div>

        <div class="form-group row">
          <div class="col-sm-2">
            <%= f.label :description, class: "col-form-label" %>
          </div>
          <div class="col-sm-10">
            <%= f.text_area :description, class: "form-control", placeholder:"Description" %>
          </div>
        </div>

        <div class="form-group row">
          <div class="offset-sm-2 col-sm-10">
            <%= f.submit t(".update"), class: "btn btn-info" %>
          </div>
        </div>
      <% end %>
    </div>
    <!-- /.tab-pane -->
  </div>
  <!-- /.tab-content -->
</div><!-- /.card-body -->

app/views/company_projects/_leader.html.erb
<b class="d-block"><%= leader.name %></b>

app/views/company_projects/_new.html.erb
<div class="card-body" style="margin: 20px 0px;">
  <div class="tab-content">
    <div class="active tab-pane" id="settings">
      <%= form_for(@project, url: company_projects_path, class: "form-horizontal", remote: true) do |f|%>
        <%= render "shared/error_messages", object: f.object %>
        <%= f.hidden_field :path, value: @path %>
        <div class="form-group row">
          <div class="col-sm-2">
            <%= f.label :name, class: "col-form-label" %>
          </div>
          <div class="col-sm-10">
            <%= f.text_field :name, class: "form-control", placeholder:t(".project_name")%>
          </div>
        </div>

        <div class="form-group row">
          <div class="col-sm-2">
            <%= f.label :document_link, class: "col-form-label" %>
          </div>
          <div class="col-sm-10">
            <%= f.text_field :document_link, class: "form-control", placeholder:t(".document_link") %>
          </div>
        </div>

        <div class="form-group row">
          <div class="col-sm-2">
            <%= f.label :client_company, class: "col-form-label" %>
          </div>
          <div class="col-sm-4">
            <%= f.text_field :client_company, class: "form-control", placeholder:t(".client_company") %>
          </div>

          <div class="col-sm-2">
            <%= f.label :importance, class: "col-form-label" %>
          </div>
          <div class="col-sm-4">
            <%= f.select :importance, improtance_select ,{}, {class: "form-control custom-select"}  %>
          </div>
        </div>

        <div class="form-group row">
          <div class="col-sm-2">
            <%= f.label :description, class: "col-form-label" %>
          </div>
          <div class="col-sm-10">
            <%= f.text_area :description, class: "form-control", placeholder:t(".description") %>
          </div>
        </div>

        <div class="form-group row">
          <div class="offset-sm-2 col-sm-10">
            <%= f.submit t(".add_project"), class: "btn btn-success" %>
          </div>
        </div>
      <% end %>
    </div>
    <!-- /.tab-pane -->
  </div>
  <!-- /.tab-content -->
</div><!-- /.card-body -->

app/views/company_projects/_project.html.erb
<tr >
  <td>
      <%= project_counter + 1%>
  </td>
  <td>
    <a>
      <%= project.name %>
    </a>
    <br/>
    <small>
      <%= project.created_at %>
    </small>
  </td>
  <td>
    <ul class="list-inline">
      <%= render partial: "company_projects/division", collection: project.divisions.uniq %>
    </ul>
  </td>
  <td>
    <%= project.client_company %>
  </td>

  <td>
    <% if project.medium? %>
      <span class="badge badge-success"><%= project.importance %></span>
    <% else %>
      <span class="badge badge-danger"><%= project.importance %></span>
    <% end %>
  </td>

  <td class="project-actions text-right">
    <%= link_to company_project_path(project), {class: "btn btn-sm btn-primary", remote: true, "data-toggle": "modal", "data-target": "#show_dialog"} do %>
      <i class="fas fa-eye">
      </i>
      <%= t ".view"%>
    <% end %>
    <%= link_to edit_company_project_path(project), {class: "btn btn-sm btn-info", remote: true, "data-toggle": "modal", "data-target": "#show_dialog"} do %>
      <i class="fas fa-pencil-alt">
      </i>
      <%= t ".edit"%>
    <% end %>
    <%= link_to add_project_manager_path(project), {class: "btn btn-sm btn-warning", remote: true, "data-toggle": "modal", "data-target": "#show_dialog"} do %>
      <i class="fas fa-plus">
      </i>
      <%= t ".add_manager"%>
    <% end %>
    <% if project.users.where(division_id: current_division.id).present? %>
      <%= link_to add_project_division_path(project), {class: "btn btn-sm btn-success", remote: true, "data-toggle": "modal", "data-target": "#show_dialog"} do %>
        <i class="fas fa-plus">
        </i>
        <%= t ".add_department"%>
      <% end %>
    <% end %>
    <%= link_to company_project_path(project), {method: :delete, class: "btn btn-danger btn-sm",data: {confirm: "Bạn chắc chứ"}} do %>
      <i class="fas fa-trash">
      </i>
      <%= t ".delete"%>
    <% end %>
  </td>
</tr>

app/views/company_projects/_show.html.erb
<div class="card-body" style="margin: 20px 0px;">
  <div class="tab-content">
    <div class="active tab-pane" id="settings">
      <%= form_for(@project, url: company_project_path, class: "form-horizontal", remote: true) do |f|%>
        <%= render "shared/error_messages", object: f.object %>
        <%= f.hidden_field :path, value: @path %>
        <div class="form-group row">
          <div class="col-sm-2">
            <%= f.label :name, class: "col-form-label" %>
          </div>
          <div class="col-sm-10">
            <%= f.text_field :name, class: "form-control", placeholder:"Project Name", readonly: true %>
          </div>
        </div>

        <div class="form-group row">
          <div class="col-sm-2">
            <%= f.label :document_link, class: "col-form-label" %>
          </div>
          <div class="col-sm-10">
            <%= f.text_area :document_link, class: "form-control", placeholder:"Document Link", readonly: true %>
          </div>
        </div>

        <div class="form-group row">
          <div class="col-sm-2">
            <%= f.label :description, class: "col-form-label" %>
          </div>
          <div class="col-sm-10">
            <%= f.text_area :description, class: "form-control", placeholder:"Description", readonly: true %>
          </div>
        </div>

      <% end %>
    </div>
    <!-- /.tab-pane -->
  </div>
  <!-- /.tab-content -->
</div><!-- /.card-body -->

app/views/company_projects/edit.js.erb
$("#title_dialog").text("Chỉnh sửa dự án");
$(".modal-dialog.modal-dialog-centered").css("max-width", "900px");
$("#modal_body").html("<%= j(render :partial => "company_projects/edit")%>");

app/views/company_projects/index.html.erb
<div class="content-wrapper" style="background-color: #ffffff">
  <!-- Content Header (Page header) -->
  <%= render partial: "shared/head_profile", locals: {path1: overview_companys_path, title: t(".title"), link1: t(".project_manager"), link2: t(".project")}%>

  <!-- Main content -->
  <section class="content container">
    <div class="float-left" style="margin: 0 0 15px 0px;">
      <%= link_to new_company_project_path, {class: "btn btn-sm btn-info float-left", remote: true, "data-toggle": "modal", "data-target": "#show_dialog"} do %>
        <i class="fas fa-plus"></i>
        <%= t ".create_project"%>
      <% end %>
    </div>

    <div class="float-right">
      <%= search_form_for @q, url: company_projects_path, class: "form-inline" do |f| %>
        <%= f.search_field :name_cont, class: "form-control mr-sm-2", placeholder: "Search" %>
        <%= f.submit class: "btn btn-outline-success my-2 my-sm-0" do %>
          <i class="fas fa-search"></i>
        <% end %>
      <% end %>
    </div>

    <!-- Default box -->
    <div class="card" style="height: 500px; width: 100%">
      <div class="card-header" style="height: 40px;">
        <h3 class="card-title"><%= t ".title" %></h3>
        <% if @projects.blank? %>
          <h3 class="card-title" style="margin-left: 10px; color: red;">- <%= t".no_data"%></h3>
        <% end %>
      </div>
      <div class="card-body p-0">
        <table class="table table-striped projects">
            <thead>
                <tr>
                    <th style="width: 1%">
                      #
                    </th>
                    <th>
                      <%= t".project_name"%>
                    </th>
                    <th>
                      <%= t".division"%>
                    </th>
                    <th>
                      <%= t".client_company"%>
                    </th>
                    <th>
                      <%= t".importance"%>
                    </th>
                    <th class="text-center" style="width: 30%">
                      <%= t".more"%>
                    </th>
                </tr>
            </thead>
            <tbody>
              <%= render partial: "company_projects/project", collection: @projects %>
            </tbody>
        </table>
      </div>
      <!-- /.card-body -->
    </div>
    <%= will_paginate @projects%>
    <!-- /.card -->

  </section>
  <!-- /.content -->
</div>

app/views/company_projects/new.js.erb
$("#title_dialog").text("Tạo dự án mới");
$(".modal-dialog.modal-dialog-centered").css("max-width", "900px");
$("#modal_body").html("<%= j(render :partial => "company_projects/new")%>");

app/views/company_projects/show.js.erb
$("#title_dialog").text("Xem mô tả dự án");
$(".modal-dialog.modal-dialog-centered").css("max-width", "900px");
$("#modal_body").html("<%= j(render :partial => "company_projects/show")%>");